"""add_orders_tables

Revision ID: 5bcc0594f3de
Revises: 1df2004d5fde
Create Date: 2025-12-19 00:46:47.847686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bcc0594f3de'
down_revision: Union[str, None] = '1df2004d5fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_address_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'currency')
    op.add_column('payments', sa.Column('razorpay_order_id', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'provider')
    op.drop_column('payments', 'provider_payment_id')
    op.drop_index('ix_product_media_public_id', table_name='product_media')
    op.drop_column('product_media', 'public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_media', sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_product_media_public_id', 'product_media', ['public_id'], unique=False)
    op.add_column('payments', sa.Column('provider_payment_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'razorpay_payment_id')
    op.drop_column('payments', 'razorpay_order_id')
    op.add_column('orders', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_address_id_fkey', 'orders', 'addresses', ['address_id'], ['id'])
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('orders', 'updated_at')
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['id'])
    op.alter_column('order_items', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_items', 'variant_id')
    # ### end Alembic commands ###
