"""cart image and address fixed

Revision ID: d65f927b6dfb
Revises: f1a2b3c4d5e7
Create Date: 2026-05-20 14:15:59.897123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65f927b6dfb'
down_revision: Union[str, None] = 'f1a2b3c4d5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_product_media_product_id'), table_name='product_media')
    op.drop_index(op.f('idx_product_media_variant_id'), table_name='product_media')
    op.drop_index(op.f('idx_product_option_items_option_id'), table_name='product_option_items')
    op.drop_column('product_option_items', 'price')
    op.drop_index(op.f('idx_product_options_product_id'), table_name='product_options')
    op.drop_index(op.f('idx_product_variants_option1'), table_name='product_variants')
    op.drop_index(op.f('idx_product_variants_option2'), table_name='product_variants')
    op.drop_index(op.f('idx_product_variants_option3'), table_name='product_variants')
    op.drop_index(op.f('idx_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('idx_products_category'), table_name='products')
    op.drop_index(op.f('idx_products_id'), table_name='products')
    op.drop_index(op.f('idx_products_product_type'), table_name='products')
    op.drop_index(op.f('idx_products_status'), table_name='products')
    op.drop_index(op.f('idx_products_status_type'), table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_products_status_type'), 'products', ['status', 'product_type'], unique=False)
    op.create_index(op.f('idx_products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('idx_products_product_type'), 'products', ['product_type'], unique=False)
    op.create_index(op.f('idx_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('idx_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('idx_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('idx_product_variants_option3'), 'product_variants', ['option3'], unique=False)
    op.create_index(op.f('idx_product_variants_option2'), 'product_variants', ['option2'], unique=False)
    op.create_index(op.f('idx_product_variants_option1'), 'product_variants', ['option1'], unique=False)
    op.create_index(op.f('idx_product_options_product_id'), 'product_options', ['product_id'], unique=False)
    op.add_column('product_option_items', sa.Column('price', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_product_option_items_option_id'), 'product_option_items', ['option_id'], unique=False)
    op.create_index(op.f('idx_product_media_variant_id'), 'product_media', ['variant_id'], unique=False)
    op.create_index(op.f('idx_product_media_product_id'), 'product_media', ['product_id'], unique=False)
    # ### end Alembic commands ###
